-- ==============================================================================
-- SUPABASE SCHEMA FOR JARVISIA2 (PostgreSQL)
-- Copia y ejecuta este script completo en el SQL Editor de tu proyecto Supabase.
-- ==============================================================================

-- 1. TABLA DE USUARIOS
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    name TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 2. TABLA DE CATEGORÍAS
CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL DEFAULT 1,
    name TEXT NOT NULL,
    color TEXT NOT NULL DEFAULT '#3b82f6',
    description TEXT,
    CONSTRAINT unique_user_category UNIQUE(user_id, name)
);

-- 3. TABLA DE ÁREAS
CREATE TABLE IF NOT EXISTS areas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL DEFAULT 1,
    name TEXT NOT NULL,
    color TEXT NOT NULL DEFAULT '#8b5cf6',
    icon TEXT NOT NULL DEFAULT 'fa-layer-group',
    description TEXT,
    CONSTRAINT unique_user_area UNIQUE(user_id, name)
);

-- 4. TABLA DE REGLAS
CREATE TABLE IF NOT EXISTS rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL DEFAULT 1,
    keyword TEXT NOT NULL,
    target_type TEXT NOT NULL,
    target_value TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 5. TABLA DE DUMPS
CREATE TABLE IF NOT EXISTS dumps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL DEFAULT 1,
    original_text TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 6. TABLA DE ITEMS / TAREAS
CREATE TABLE IF NOT EXISTS items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL DEFAULT 1,
    dump_id BIGINT,
    title TEXT NOT NULL,
    category TEXT NOT NULL DEFAULT 'tarea',
    status TEXT NOT NULL DEFAULT 'pendiente',
    priority TEXT NOT NULL DEFAULT 'media',
    area TEXT,
    due_date TEXT,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 7. TABLA DE FACULTAD / MATERIAS
CREATE TABLE IF NOT EXISTS facu_materias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL DEFAULT 1,
    name TEXT NOT NULL,
    abbreviation TEXT,
    cursado TEXT DEFAULT 'C',
    level TEXT DEFAULT 'I',
    correlativa_cursada TEXT,
    correlativa_aprobada TEXT,
    status TEXT NOT NULL DEFAULT 'Cursando',
    grade DOUBLE PRECISION,
    condition_detail TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 8. TABLA DE FINANZAS
CREATE TABLE IF NOT EXISTS finanzas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL DEFAULT 1,
    type TEXT NOT NULL,
    fecha_alta TEXT,
    fecha_pago TEXT NOT NULL,
    description TEXT NOT NULL,
    amount DOUBLE PRECISION NOT NULL,
    category TEXT NOT NULL DEFAULT 'Varios',
    payment_method TEXT NOT NULL DEFAULT 'Efectivo',
    paid_to TEXT,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 9. TABLA DE INVERSIONES
CREATE TABLE IF NOT EXISTS inversiones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL DEFAULT 1,
    fecha TEXT,
    description TEXT NOT NULL,
    platform TEXT,
    buy_price DOUBLE PRECISION,
    quantity DOUBLE PRECISION,
    current_val DOUBLE PRECISION,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 10. TABLA DE PEDIDOS 3D
CREATE TABLE IF NOT EXISTS pedidos3d (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL DEFAULT 1,
    client TEXT NOT NULL,
    seller TEXT,
    product TEXT NOT NULL,
    order_date TEXT NOT NULL,
    delivery_date TEXT,
    price DOUBLE PRECISION,
    time_str TEXT,
    grams_str TEXT,
    hours DOUBLE PRECISION,
    status TEXT NOT NULL DEFAULT 'Diseño',
    priority TEXT NOT NULL DEFAULT 'media',
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- ==============================================================================
-- SEMILLA DE DATOS INICIALES (SEED DATA)
-- ==============================================================================

-- Usuario admin (password: 1234 hash SHA256: 03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4)
INSERT INTO users (username, password_hash, name)
VALUES ('admin', '03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4', 'Lau Admin')
ON CONFLICT (username) DO NOTHING;

-- Categorías por defecto
INSERT INTO categories (user_id, name, color, description) VALUES
(1, 'tarea',        '#3b82f6', 'Acción concreta a realizar'),
(1, 'proyecto',     '#8b5cf6', 'Conjunto de tareas relacionadas'),
(1, 'idea',         '#f59e0b', 'Pensamiento o iniciativa futura'),
(1, 'nota',         '#06b6d4', 'Información de referencia'),
(1, 'recordatorio', '#10b981', 'Fecha o evento a no olvidar'),
(1, 'área',         '#ec4899', 'Responsabilidad o rol principal')
ON CONFLICT (user_id, name) DO NOTHING;

-- Áreas por defecto
INSERT INTO areas (user_id, name, color, icon, description) VALUES
(1, 'Facultad',         '#8b5cf6', 'fa-graduation-cap', 'Materias y exámenes'),
(1, 'Emprendimiento 3D','#ec4899', 'fa-cube',           'Pedidos e impresiones 3D'),
(1, 'Finanzas',         '#10b981', 'fa-wallet',         'Gastos e ingresos'),
(1, 'Personal',         '#3b82f6', 'fa-user',           'Tareas personales'),
(1, 'Trabajo',          '#f59e0b', 'fa-briefcase',      'Responsabilidades laborales')
ON CONFLICT (user_id, name) DO NOTHING;

-- Reglas por defecto
INSERT INTO rules (user_id, keyword, target_type, target_value) VALUES
(1, 'facultad',    'area',     'Facultad'),
(1, 'materia',     'area',     'Facultad'),
(1, 'parcial',     'area',     'Facultad'),
(1, 'examen',      'area',     'Facultad'),
(1, 'cursada',     'area',     'Facultad'),
(1, '3d',          'area',     'Emprendimiento 3D'),
(1, 'impresora',   'area',     'Emprendimiento 3D'),
(1, 'filamento',   'area',     'Emprendimiento 3D'),
(1, 'imprimir',    'area',     'Emprendimiento 3D'),
(1, 'modelar',     'area',     'Emprendimiento 3D'),
(1, 'pedido',      'area',     'Emprendimiento 3D'),
(1, 'repuesto',    'area',     'Emprendimiento 3D'),
(1, 'pesos',       'area',     'Finanzas'),
(1, 'precio',      'area',     'Finanzas'),
(1, 'pagar',       'area',     'Finanzas'),
(1, 'gasto',       'area',     'Finanzas'),
(1, 'cobrar',      'area',     'Finanzas'),
(1, 'casa',        'area',     'Personal'),
(1, 'comprar',     'area',     'Personal'),
(1, 'idea',        'category', 'idea'),
(1, 'se me ocurrió','category','idea'),
(1, 'estaría bueno','category','idea'),
(1, 'recordar',    'category', 'recordatorio'),
(1, 'no olvidar',  'category', 'recordatorio'),
(1, 'nota',        'category', 'nota'),
(1, 'clave',       'category', 'nota'),
(1, 'contraseña',  'category', 'nota'),
(1, 'urgente',     'priority', 'alta'),
(1, 'hoy',         'priority', 'alta'),
(1, 'ya',          'priority', 'alta'),
(1, 'asap',        'priority', 'alta'),
(1, 'con tiempo',  'priority', 'baja'),
(1, 'después',     'priority', 'baja'),
(1, 'cuando pueda','priority', 'baja'),
(1, 'computadora', 'context',  'computadora'),
(1, 'pc',          'context',  'computadora'),
(1, 'taller',      'context',  'taller 3D')
ON CONFLICT DO NOTHING;
